# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89c7425cb7f278bef1cf23b7955a715c3e0df0eb2551cb476f7ec730dbfc90ca4e2612e931f232a8be77b6eaba1d79f3cc0175ad03b61e149ad037c0df814303

test:
  secret_key_base: 0866f6b83f75bc12103091a44395f7aaf515ecb8da9943e276b0f32346e5278cb9ae168e7321aabe05f238141a22ad2ece07ea29495903456e9ee022cedafa87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
